services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
      timeout: 3s
      retries: 10

  redis:
    image: redis:6.2.4-alpine
#    ports:
#      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 1s
      retries: 5
    depends_on:
      - db

  backend:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    environment:
      POSTGRES_HOST: db
      REDIS_URL: "redis://redis:6379"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
#    ports:
#      - "8000:8000"

  static_collector:
    build: .
    command: bash -c "python manage.py collectstatic -c --no-input"
    env_file: .env
    volumes:
      - django_static:/app/static

  web:
    image: nginx:1.19.3
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
      static_collector:
        condition: service_completed_successfully
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static/

  celery:
    build: .
    env_file: .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
      POSTGRES_HOST: db
    depends_on:
      backend:
        condition: service_started
    command: celery -A config worker -l info

  celery-beat:
    build: .
    env_file: .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
      POSTGRES_HOST: db
    depends_on:
      backend:
        condition: service_started
    command: celery -A config beat -l info

volumes:
  postgres_data:
  django_static:
